source 'https://rubygems.org'

gem 'eventmachine'
gem 'eventmachine_httpserver', :require => 'evma_httpserver'
gem 'em-websocket'
gem 'json'
gem 'rumouse'
gem 'posix-spawn'
gem 'pry'
gem 'pry-byebug'
gem 'websocket-eventmachine-client'